### ISSUE TITLE
Error: @esx_vehicleshop/client/main.lua:147: bad argument #1 to ‘insert’ (table expected, got nil)

### ISSUE THREAD

**Issue by Shad0wyDr3ams** [iLeaksy/fivem-vehicle-list#4]
this pops up when i go to buy at the vehicleshop. i even followed instructions to a t.

**Comment by callmeijoe** [comment]
> this pops up when i go to buy at the vehicleshop. i even followed instructions to a t.

In database. Change "vehicles_category" to "vehicle_categories".

**Comment by Shad0wyDr3ams** [comment]
changed it but now when i goto the vehicle shop and enter it just sits on an overhead view with no cars showing

**Comment by Shad0wyDr3ams** [comment]
and there are no errors in the f8 console
